export const apiRoutes = {
  login: "/api/auth/login",
  register: "/api/auth/register",
  photos: "/api/photos",
  followingPhotos: "/api/photos/following",
  users: "/api/users",
  myUser: "/api/users/me",
  updateProfile: "/api/users/update-profile-data",
  updateProfilePicture: "/api/users/update-profile-picture",
  followUser: "/api/users/follow/:targetUserId",
  userFollowers: "/api/users/:userId/followers",
  userFollowing: "/api/users/:userId/following",
  userFollowCounts: "/api/users/:userId/follow-counts",
  userFollowState: "/api/users/:targetUserId/follow-state",
  likePhoto: "/api/photos/like/:photoId",
  addComment: "/api/photos/comment/:photoId",
  addReply: "/api/photos/comment/:photoId/reply/:commentId",
}
